version: '3'

services:

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}-management
    volumes:
     - rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    env_file:
      - compose-rabbitmq.env
      - compose-rabbitmq.env.local
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - svcnet

volumes:

  rabbitmq-data:
    driver: local
