version: '3'

services:

  eventstore:
    image: eventstore/eventstore:release-$EVENTSTORE_VERSION
    volumes:
      - eventstore-data:/var/lib/eventstore
    env_file:
      - compose-eventstore.env
      - compose-eventstore.env.local
    ports:
      - 1113:1113
      - 2113:2113
    networks:
      - svcnet

volumes:

  eventstore-data:
    driver: local
