version: '2'

services:

  eventstore:
    image: eventstore/eventstore:release-$EVENTSTORE_VERSION
    #volumes:
    #  - ./eventstore/data:/var/lib/eventstore
    ports:
      - 1113:1113
      - 2113:2113
    networks:
      - svcnet
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
