version: '3'

services:

  postgres:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - compose-postgres.env
      - compose-postgres.env.local
    ports:
      - 5432:5432
    networks:
      - svcnet

volumes:

  postgres-data:
    driver: local
