version: '3'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:${SQLSERVER_VERSION}
    volumes:
      - sqlserver-data:/var/opt/mssql
    env_file:
      - compose-sqlserver.env
      - compose-sqlserver.env.local
    ports:
      - 1433:1433
    networks:
      - svcnet

volumes:

  sqlserver-data:
    driver: local
