version: '3'

services:

  mongo:
    image: mongo:$MONGO_VERSION
    volumes:
      - mongo-data:/data/db
    env_file:
      - compose-mongo.env
      - compose-mongo.env.local
    ports:
      - 27017:27017
    networks:
      - svcnet

volumes:

  mongo-data:
    driver: local
