version: '3'

services:

  rabbitmq:
    image: mcr.microsoft.com/mssql/server:${SQLSERVER_VERSION}
    #volumes:
    #  - ./mssql/data:/var/opt/mssql
    env_file:
      - compose-sqlserver.env
      - compose-sqlserver.env.local
    ports:
      - 1433:1433
    networks:
      - svcnet
