version: '3'

services:

  mongo:
    image: mongo:$MONGO_VERSION
    #volumes:
    #  MongoDB uses memory mapped files, this is not compatible with Docker for Windows volumes sharing
    #  - ./mongo/data/db:/data/db
    #environment:
    # MONGO_INITDB_ROOT_USERNAME: root
    # MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - svcnet
