version: '3'

services:

  redis:
    image: redis:$REDIS_VERSION
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - svcnet

volumes:

  redis-data:
    driver: local
