version: '3'

services:

  mongo:
    image: mongo:$MONGO_VERSION
    #volumes:
    #  MongoDB uses memory mapped files, this is not compatible with Docker for Windows volumes sharing
    #  - ./mongo/data/db:/data/db
    env_file:
      - compose-mongo.env
      - compose-mongo.env.local
    ports:
      - 27017:27017
    networks:
      - svcnet
