version: '3'

services:

  redis:
    image: redis:$REDIS_VERSION
    volumes:
      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
      #- ./redis/data:/data
    ports:
      - 6379:6379
    networks:
      - svcnet
