export ELK_VERSION=7.1.1
export MONGO_VERSION=4.0
export RABBITMQ_VERSION=3.7
export REDIS_VERSION=4.0
export EVENTSTORE_VERSION=5.0.0
export SQLSERVER_VERSION=2017-latest
export POSTGRES_VERSION=11.1
export VAULT_VERSION=1.1.2
