version: "3"

services:
  seq:
    image: datalust/seq:5.1
    volumes:
      - seq-data:/data
    env_file:
      - seq-5.1/service.env
      - ../.env/seq-5.1.env
    ports:
      - 5340:80
      - 5341:5341
    networks:
      - devsvcnet

volumes:
  seq-data:
    driver: local
