version: "3"

services:
  logstash:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/logstash/logstash:8.3.0
    volumes:
      - ./logstash-8.3/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash-8.3/pipeline:/usr/share/logstash/pipeline:ro
    env_file:
      - logstash-8.3/service.env
      - ../.env/logstash-8.3.env
    ports:
      - 5000:5000
    networks:
      - devsvcnet
