version: '3'

services:

  mongo:
    image: mongo:4.2.1
    volumes:
      - mongo-data:/data/db
    env_file:
      - mongo.env
    ports:
      - 27017:27017
    networks:
      - devsvcnet

volumes:

  mongo-data:
    driver: local
