version: '3'

services:

  postgres:
    image: postgres:12.1
    volumes:
      - postgres-data:/var/lib/postgresql
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    networks:
      - devsvcnet

volumes:

  postgres-data:
    driver: local
