version: '3'

services:

  rabbitmq:
    image: rabbitmq:3.8-management
    volumes:
     - rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    env_file:
      - rabbitmq.env
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - devsvcnet

volumes:

  rabbitmq-data:
    driver: local
