version: '3'

services:

  redis:
    image: redis:5.0
    volumes:
      - redis-data:/data
    env_file:
      - redis.env
    ports:
      - 6379:6379
    networks:
      - devsvcnet

volumes:

  redis-data:
    driver: local
