version: '3'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - sqlserver-data:/var/opt/mssql
    env_file:
      - sqlserver.env
    ports:
      - 1433:1433
    networks:
      - devsvcnet

volumes:

  sqlserver-data:
    driver: local
