version: '3'

services:

  vault:
    image: vault:1.3.0
    volumes:
      - ../services/vault/config:/vault/config
      - vault-data:/vault/file
    entrypoint: vault server -dev -dev-kv-v1 -config=/vault/config/vault.json
    env_file:
      - vault.env
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
      - 8201:8201
    networks:
      - devsvcnet

volumes:

  vault-data:
    driver: local
