version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.1
    volumes:
      - ./elasticsearch-8.3/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch-data:/usr/share/elasticsearch/data
    env_file:
      - elasticsearch-8.3/service.env
      - ../.env/elasticsearch-8.3.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - devsvcnet

volumes:
  elasticsearch-data:
    driver: local
