version: "3"

services:
  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    env_file:
      - mongo-4.4/service.env
      - ../.env/mongo-4.4.env
    ports:
      - 27017:27017
    networks:
      - devsvcnet

volumes:
  mongo-data:
    driver: local
