version: "3"

services:
  eventstore:
    image: eventstore/eventstore:21.10.5-buster-slim
    volumes:
      - eventstore-data:/var/lib/eventstore
    env_file:
      - eventstore-21.10/service.env
      - ../.env/eventstore-21.10.env
    ports:
      - 1113:1113
      - 2113:2113
    networks:
      - devsvcnet

volumes:
  eventstore-data:
    driver: local
