version: "3"

services:
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.3.0
    volumes:
      - ./kibana-8.3/config/:/usr/share/kibana/config:ro
    env_file:
      - kibana-8.3/service.env
      - ../.env/kibana-8.3.env
    ports:
      - 5601:5601
    networks:
      - devsvcnet
