version: "3"

services:
  mongo:
    image: mongo:5.0
    volumes:
      - mongo-data:/data/db
    env_file:
      - mongo-5.0/service.env
      - ../.env/mongo-5.0.env
    ports:
      - 27017:27017
    networks:
      - devsvcnet

volumes:
  mongo-data:
    driver: local
