version: '3'

services:

  vault:
    image: vault:1.3.0
    volumes:
      - ./vault-1.3/config:/vault/config
      - vault-data:/vault/file
    entrypoint: vault server -dev -dev-kv-v1 -config=/vault/config/vault.json
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
    env_file:
      - ../.env/vault-1.3.env
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
      - 8201:8201
    networks:
      - devsvcnet

volumes:

  vault-data:
    driver: local
