version: "3"

services:
  redis:
    image: redis:7.0
    volumes:
      - redis-data:/data
    env_file:
      - redis-7.0/service.env
      - ../.env/redis-7.0.env
    ports:
      - 6379:6379
    networks:
      - devsvcnet

volumes:
  redis-data:
    driver: local
