version: '3'

services:

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.6.2
    volumes:
      - ./kibana-7.6/config/:/usr/share/kibana/config:ro
    env_file:
      - kibana-7.6/service.env
      - ../.env/kibana-7.6.env
    ports:
      - 5601:5601
    networks:
      - devsvcnet
